version = 1

test_patterns = ["*/tests/**"]

exclude_patterns = ["dist/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest"
  ]
  style_guide = "airbnb"
  dialect = "typescript"