version: '3'
services:
    redis:
        image: redis
        networks:
            - webnet

    db:
        image: postgres
        networks:
            - webnet
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: postgres
            POSTGRES_DB: karobaar
        ports:
            - '5432:5432'

    web:
        image: karobaar1.1
        ports:
            - '4000:4000'
        networks:
            - webnet
        environment:
            DB_HOST: db
            REDIS_HOST: redis
            DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/karobaar
        command: ['node', 'dist/index.js']

networks:
    webnet:
